export const data = [
  {
    id: 1,
    name: "Spaghetti Bolognese",
    description:
      "Classic Italian dish with a rich tomato-based sauce and ground beef",
    image: "https://i.imgur.com/mivLRhO.jpeg",
    steps: [
      "Cook the spaghetti according to package instructions.",
      "In a large skillet, brown the ground beef over medium heat.",
      "Add the onion, garlic, and carrot and cook until softened.",
      "Stir in the tomato paste, canned tomatoes, and herbs.",
      "Simmer for 20-30 minutes until the sauce has thickened.",
      "Serve the spaghetti with the bolognese sauce on top.",
    ],
    tags: ["Italian", "Pasta", "Dinner"],
    ingredients: [
      "Spaghetti, 1 pound",
      "Ground beef, 1 pound",
      "Onion, 1 chopped",
      "Garlic, 3 cloves minced",
      "Carrot, 1 chopped",
      "Tomato paste, 1 tablespoon",
      "Canned tomatoes, 28 ounces",
      "Dried herbs, 1 tablespoon, such as oregano and basil",
    ],
  },
  {
    id: 2,
    name: "Caesar Salad",
    description:
      "Classic salad made with romaine lettuce, croutons, Parmesan cheese, and a creamy dressing",
    image: "https://i.imgur.com/sL6pXV4.jpeg",
    steps: [
      "Wash and dry the lettuce leaves and tear them into bite-sized pieces.",
      "Make the dressing by whisking together anchovy paste, garlic, lemon juice, egg yolks, and oil.",
      "Toss the lettuce with the dressing and top with croutons and shaved Parmesan cheese.",
    ],
    tags: ["Salad", "Vegetarian"],
    ingredients: [
      "Romaine lettuce, 1 head",
      "Croutons, 1 cup",
      "Parmesan cheese, shaved, 1 cup",
      "Anchovy paste, 2 tablespoons",
      "Garlic, 2 cloves minced",
      "Lemon juice, 1/4 cup",
      "Egg yolks, 2",
      "Olive oil, 1/2 cup",
    ],
  },
  {
    id: 3,
    name: "Chicken Tikka Masala",
    description:
      "Indian curry dish made with marinated chicken in a creamy tomato-based sauce",
    image: "https://i.imgur.com/nY0ntwD.jpeg",
    steps: [
      "Marinate the chicken with yogurt, spices, and lemon juice for at least 1 hour.",
      "Grill or broil the chicken until cooked through.",
      "In a separate pot, sauté onions, garlic, and ginger until softened.",
      "Add canned tomatoes and spices, and cook for 5 minutes.",
      "Stir in cream or coconut milk and the cooked chicken, and simmer for 10-15 minutes.",
      "Serve with rice or naan bread.",
    ],
    tags: ["Indian", "Chicken", "Dinner"],
    ingredients: [
      "Boneless, skinless chicken thighs, 1 pound",
      "Yogurt, 1 cup",
      "Lemon juice, 2 tablespoons",
      "Ginger, 1 tablespoon minced",
      "Garlic, 3 cloves minced",
      "Onion, 1 chopped",
      "Canned tomatoes, 14 ounces",
      "Garam masala, 1 tablespoon",
      "Paprika, 1 teaspoon",
      "Turmeric, 1 teaspoon",
      "Cumin, 1 teaspoon",
      "Coriander, 1 teaspoon",
      "Cream or coconut milk, 1 cup",
    ],
  },
  {
    id: 4,
    name: "Chocolate Brownies",
    description:
      "Rich and fudgy chocolate dessert with a crispy top layer and a gooey center",
    image: "https://i.imgur.com/mSK4WtF.jpeg",
    steps: [
      "Preheat the oven to 350°F (175°C) and grease a baking pan.",
      "Melt the butter and chocolate in a saucepan over low heat.",
      "In a separate bowl, whisk together eggs, sugar, and vanilla extract until smooth.",
      "Add the chocolate mixture and stir to combine.",
      "Sift in flour and cocoa powder, and fold gently until just combined.",
      "Pour the batter into the prepared pan and bake for 25-30 minutes.",
      "Allow to cool for 10 minutes before slicing into squares.",
      "Serve with a dollop of whipped cream or vanilla ice cream.",
    ],
    tags: ["Dessert", "Chocolate"],
    ingredients: [
      "Unsalted butter, 1 cup",
      "Semi-sweet chocolate, 8 ounces",
      "Eggs, 4",
      "Granulated sugar, 1 1/4 cups",
      "Vanilla extract, 2 teaspoons",
      "All-purpose flour, 3/4 cup",
      "Cocoa powder, 1/4 cup",
    ],
  },
  {
    id: 5,
    name: "Rasgulla",
    description:
      "Rasgulla is a popular Indian dessert made by curdling milk into small balls that are then cooked in a sugar syrup. It is a spongy and sweet dessert that is often served chilled and is enjoyed by people of all ages.",
    image: "https://i.imgur.com/wm8Xwyu.jpeg",
    steps: [
      "In a heavy-bottomed pan, bring the milk to a boil. Once it starts boiling, reduce the heat to low and add the lemon juice or vinegar slowly, stirring continuously until the milk curdles.",
      "Turn off the heat and let it sit for 2-3 minutes. Then, strain the curdled milk through a muslin cloth or a cheesecloth.",
      "Rinse the chenna (curdled milk) under cold running water to remove the lemon juice or vinegar taste.",
      "Tie the cloth with chenna and hang it for 30-45 minutes to drain out the excess water.",
      "After 45 minutes, take the chenna out and knead it well for about 10-15 minutes or until it becomes smooth.",
      "Divide the kneaded chenna into small balls and roll them gently between your palms to make smooth, crack-free balls.",
      "In a separate pot, add the sugar, water, cardamom powder, and saffron (if using) and bring it to a boil.",
      "Add the chenna balls to the sugar syrup and cover the pot with a lid. Cook for 15-20 minutes on medium heat.",
      "Turn off the heat and let it cool completely. You can also refrigerate it for a few hours before serving.",
      "Serve the rasgulla chilled and enjoy!",
    ],
    tags: ["Indian", "Dessert"],
    ingredients: [
      "Milk, 1 liter",
      "Lemon juice or vinegar, 2-3 tablespoons",
      "Sugar, 2 cups",
      "Water, 4 cups",
      "Cardamom powder, 1/4 teaspoon",
      "Saffron (optional), a few strands",
    ],
  },
  {
    id: 6,
    name: "Beef Stroganoff",
    description: "Russian dish with beef and sour cream sauce",
    image: "https://i.imgur.com/inMOV4I.jpeg",
    steps: [
      "Cook the egg noodles according to package instructions.",
      "In a large skillet, cook the beef until browned.",
      "Add the onion and cook until softened.",
      "Stir in the mushrooms and cook until tender.",
      "Add the beef broth and simmer for 10-15 minutes.",
      "Stir in the sour cream and heat through.",
      "Serve the egg noodles with the beef stroganoff sauce on top.",
    ],
    tags: ["Russian", "Beef", "Dinner"],
    ingredients: [
      "Egg noodles, 8 oz",
      "Beef sirloin, 1 lb",
      "Onion, 1 medium",
      "Mushrooms, 8 oz",
      "Beef broth, 1 cup",
      "Sour cream, 1 cup",
    ],
  },
  {
    id: 7,
    name: "Samosa",
    description:
      "Samosa is a popular Indian snack that is loved by many. It is a crispy, triangular pastry filled with spiced potatoes, peas, and sometimes other vegetables. It is usually served with chutney and can be enjoyed as a snack or a light meal. Making samosas at home is easy, and the result is a delicious, hot and fresh snack that can be enjoyed anytime.",
    image: "https://i.imgur.com/IDHOT3n.jpeg",
    steps: [
      "In a pan, heat some oil and add cumin seeds. Let them splutter.",
      "Add onions and green chilli. Saute until the onions turn translucent.",
      "Add ginger and saute for a few seconds.",
      "Add the boiled and mashed potatoes and boiled green peas. Mix well.",
      "Add coriander powder, garam masala, amchur powder, red chilli powder, and salt. Mix well and cook for a few minutes.",
      "Remove from heat and let the mixture cool down.",
      "In a mixing bowl, add all-purpose flour, ajwain seeds, salt, and oil. Mix well.",
      "Add water slowly and knead the dough until it is smooth and elastic.",
      "Cover the dough with a damp cloth and let it rest for 20-30 minutes.",
      "After the dough has rested, divide it into small balls and roll each ball into a small circle.",
      "Cut the circle into two halves using a knife.",
      "Take one half and form a cone by overlapping the cut edges and sealing them with a little water.",
      "Fill the cone with 1-2 tbsp of the potato filling and seal the top edge of the cone with a little water.",
      "Repeat with the rest of the dough and filling.",
      "Heat oil in a deep frying pan. Once the oil is hot, reduce the heat to medium and add the samosas.",
      "Fry the samosas until they are golden brown and crisp.",
      "Remove them from the oil and place them on a paper towel to remove excess oil.",
      "Serve the samosas hot with your favorite chutney or sauce. Enjoy!",
    ],
    tags: ["Indian", "Samosa", "Snack"],
    ingredients: [
      "2 cups all-purpose flour",
      "2 tablespoons vegetable oil",
      "1/2 teaspoon salt",
      "1/2 teaspoon ajwain seeds (optional)",
      "1/2 cup water",
      "2 tablespoons vegetable oil",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon fennel seeds",
      "1/2 teaspoon coriander seeds",
      "1 onion, finely chopped",
      "1 tablespoon grated ginger",
      "2 garlic cloves, minced",
      "2-3 potatoes, boiled and mashed",
      "1/2 cup green peas (fresh or frozen)",
      "1 teaspoon garam masala",
      "1/2 teaspoon red chili powder",
      "1/2 teaspoon turmeric powder",
      "Salt to taste",
      "2 tablespoons chopped fresh cilantro leaves",
      "oil",
    ],
  },
]
